config/routes.rb
SecondRorApp::Application.routes.draw do
  resources :shortposts

  resources :users

end

app/models/shortpost.rb
class Shortpost < ActiveRecord::Base
  attr_accessible :spost, :usr_id
  belongs_to :user
  validates :spost, :length => { :maximum => 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :shortposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shortposts_controller.rb
class ShortpostsController < ApplicationController
  # GET /shortposts
  # GET /shortposts.json
  def index
    @shortposts = Shortpost.all
  end

  # GET /shortposts/1
  # GET /shortposts/1.json
  def show
    @shortpost = Shortpost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shortpost }
    end
  end

  # GET /shortposts/new
  # GET /shortposts/new.json
  def new
    @shortpost = Shortpost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shortpost }
    end
  end

  # GET /shortposts/1/edit
  def edit
    @shortpost = Shortpost.find(params[:id])
  end

  # POST /shortposts
  # POST /shortposts.json
  def create
    @shortpost = Shortpost.new(params[:shortpost])

    respond_to do |format|
      if @shortpost.save
        format.html { redirect_to @shortpost, notice: 'Shortpost was successfully created.' }
        format.json { render json: @shortpost, status: :created, location: @shortpost }
      else
        format.html { render action: "new" }
        format.json { render json: @shortpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shortposts/1
  # PUT /shortposts/1.json
  def update
    @shortpost = Shortpost.find(params[:id])

    respond_to do |format|
      if @shortpost.update_attributes(params[:shortpost])
        format.html { redirect_to @shortpost, notice: 'Shortpost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shortpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shortposts/1
  # DELETE /shortposts/1.json
  def destroy
    @shortpost = Shortpost.find(params[:id])
    @shortpost.destroy

    respond_to do |format|
      format.html { redirect_to shortposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all    
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortposts_helper.rb
module ShortpostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecondRorApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shortposts/_form.html.erb
<%= form_for(@shortpost) do |f| %>
  <% if @shortpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortpost.errors.count, "error") %> prohibited this shortpost from being saved:</h2>

      <ul>
      <% @shortpost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spost %><br />
    <%= f.text_field :spost %>
  </div>
  <div class="field">
    <%= f.label :usr_id %><br />
    <%= f.number_field :usr_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shortposts/edit.html.erb
<h1>Editing shortpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @shortpost %> |
<%= link_to 'Back', shortposts_path %>

app/views/shortposts/index.html.erb
<h1>Listing shortposts</h1>

<table>
  <tr>
    <th>Spost</th>
    <th>Usr</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shortposts.each do |shortpost| %>
  <tr>
    <td><%= shortpost.spost %></td>
    <td><%= shortpost.usr_id %></td>
    <td><%= link_to 'Show', shortpost %></td>
    <td><%= link_to 'Edit', edit_shortpost_path(shortpost) %></td>
    <td><%= link_to 'Destroy', shortpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shortpost', new_shortpost_path %>

app/views/shortposts/new.html.erb
<h1>New shortpost</h1>

<%= render 'form' %>

<%= link_to 'Back', shortposts_path %>

app/views/shortposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spost:</b>
  <%= @shortpost.spost %>
</p>

<p>
  <b>Usr:</b>
  <%= @shortpost.usr_id %>
</p>


<%= link_to 'Edit', edit_shortpost_path(@shortpost) %> |
<%= link_to 'Back', shortposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>